# Generated by Django 3.2.8 on 2021-10-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7_EventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventTime',
            field=models.DateField(),
        ),
    ]
