# Generated by Django 3.2.8 on 2021-10-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app7_EventApp', '0002_alter_event_eventtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventDescription',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventTime',
            new_name='Time',
        ),
    ]
