# Generated by Django 3.2.7 on 2021-11-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_remove_todoitem_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['is_completed']},
        ),
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
