# Generated by Django 3.2.8 on 2021-10-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpertanyaan',
            name='tag',
        ),
    ]
