# Generated by Django 3.2.8 on 2021-10-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forumpertanyaan_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurahanHati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('pekerjaan', models.CharField(max_length=100)),
                ('konten', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoPandemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('pekerjaan', models.CharField(max_length=100)),
                ('konten', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipsKesehatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('pekerjaan', models.CharField(max_length=100)),
                ('konten', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ForumPertanyaan',
        ),
    ]
