# Generated by Django 3.2.8 on 2021-11-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchedcoviddata',
            name='user',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
