# Generated by Django 3.2.8 on 2021-11-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0003_alter_searchedcoviddata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchedcoviddata',
            old_name='user',
            new_name='author',
        ),
    ]
