# Generated by Django 3.2.8 on 2021-11-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20211104_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matkul',
            name='day',
            field=models.CharField(blank=True, default='Monday', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matkul',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matkul',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matkul',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
