# Generated by Django 3.2.8 on 2021-11-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20211104_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matkul',
            name='day',
            field=models.CharField(default='Monday', max_length=255),
        ),
        migrations.AlterField(
            model_name='matkul',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='matkul',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='matkul',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
