# Generated by Django 3.2.8 on 2021-11-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20211104_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matkul',
            name='day',
            field=models.CharField(max_length=255),
        ),
    ]
